language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'

before_script:
  - cp .env.travis .env
  - mysql -e 'create database test_db;'
  - php artisan migrate:refresh --seed

sudo: false

install:
  - composer self-update
  - composer install
